@php
    $tanggal = $purchaseOrder->tgl_po ? \Carbon\Carbon::parse($purchaseOrder->tgl_po) : null;
    $total = (float) $purchaseOrder->items->sum(fn ($item) => (float) $item->jumlah);
    $status = $purchaseOrder->status?->value ?? $purchaseOrder->status;
@endphp
<!doctype html><html lang="id"><head><meta charset="utf-8"><style>
@page{margin:1.5cm}body{font-family:Arial,sans-serif;font-size:11px;color:#111}table{width:100%;border-collapse:collapse}td,th{padding:4px 8px;vertical-align:top}.box td,.box th{border:1px solid #ccc}.company{font-size:13px;font-weight:bold}.title{font-size:18px;font-weight:bold;text-align:center}.items th{background:#f5f5f5;text-align:center;font-weight:bold}.right{text-align:right}.center{text-align:center}.summary{width:42%;margin-left:auto;margin-top:8px}.summary td{border:1px solid #ccc}.label{background:#f5f5f5;font-weight:bold}.sign td{height:92px;text-align:center;vertical-align:bottom}.qr{position:fixed;right:0;bottom:0;text-align:center;font-size:9px}
</style></head><body>
<table class="box"><tr><td style="width:55%"><div class="company">PT. NUSANTARA ABADI JAYA</div><div>JL. Wiyata No. 81 RT 23</div><div>Kalimantan Timur</div></td><td><div class="title">PURCHASE ORDER</div><table><tr><td style="border:0;width:70px">No</td><td style="border:0">: {{ $purchaseOrder->no_purchase_order }}</td></tr><tr><td style="border:0">Tanggal</td><td style="border:0">: {{ $tanggal?->translatedFormat('d F Y') ?? '-' }}</td></tr></table></td></tr></table>
<table class="box" style="margin-top:10px"><tr><td><strong>Kepada Yth:</strong><br>{{ $purchaseOrder->vendor?->nama_vendor ?? '-' }}<br>{{ $purchaseOrder->vendor?->alamat ?? '-' }}@if($purchaseOrder->no_pr_customer)<br>No. PR Customer: {{ $purchaseOrder->no_pr_customer }}@endif @if($purchaseOrder->no_po_customer)<br>No. PO Customer: {{ $purchaseOrder->no_po_customer }}@endif</td></tr></table>
<table class="box items" style="margin-top:10px"><thead><tr><th style="width:28px">NO</th><th>DESKRIPSI</th><th style="width:50px">QTY</th><th style="width:45px">SAT</th><th style="width:95px">HARGA</th><th style="width:105px">JUMLAH</th></tr></thead><tbody>@foreach($purchaseOrder->items as $item)<tr><td class="center">{{ $loop->iteration }}</td><td>{{ $item->deskripsi }}</td><td class="center">{{ number_format((float) $item->qty,0,',','.') }}</td><td class="center">{{ $item->satuan }}</td><td class="right">@rupiah($item->harga_satuan)</td><td class="right">@rupiah($item->jumlah)</td></tr>@endforeach</tbody></table>
<table class="summary"><tr><td class="label">TOTAL</td><td class="right"><strong>@rupiah($total)</strong></td></tr></table>
<table class="box sign" style="margin-top:18px"><tr><td>Dibuat Oleh:<br>{{ $purchaseOrder->createdBy?->name ?? '-' }}<br><br>___________</td><td>Disetujui:<br>{{ $purchaseOrder->approvedBy?->name ?? '-' }}<br><br>___________</td></tr></table>
@if (($purchaseOrder->qr_token || isset($qrCode)) && $status === 'APPROVED')<div class="qr">@isset($qrCode)<img src="{{ $qrCode }}" style="width:80px;height:80px" alt="QR Code">@else{!! QrCode::size(80)->generate(url('/verify/' . $purchaseOrder->qr_token)) !!}@endisset</div>@endif
</body></html>
